### PR TITLE
Fixes clear command in terminal.min.js file

### PR DESCRIPTION
**Pull request by sachincool**
Fixes https://github.com/NJACKWinterOfCode/lterm/issues/2
It turns out   `clear`  command was in `jquery.terminal.min.js` so i had to edit that  And  place   
the 
```
arr[9]=1;
```
but i coudn't access the `arr[9]` variable inside the min.js file  so i had to change the `var arr`  into  `window arr`   I don't know why var didn't work , But this `window` thing was pretty cool and  worked for me.  :+1: 
in there  And that's all..  
i had to go through each file and this issue helped me get into the codebase better 
Thanks

### CODE REVIEW

**Review by Logan1x — COMMENTED** [review]
looks good, wait for fo @sr6033 to review & merge.

**Comment by sr6033** [comment]
Still, it doesn't work. It should work. I had to revert it. Have a look at it again and check if you miss somewhere.

**Comment by sachincool** [comment]
@sr6033  are you sure ? it seems to be working fine on my end.    going through "clear" > completed 
Also "Clear" > "clear" > Completed

**Comment by sachincool** [comment]
@sr6033  i tried the same changes in a newly synced/ forked repo   and it did worked,  i saw you were going through the  sarcastic "Clear" way into "clear" so i let it remain .. turns out it doesnt matter if i put arr[9]=1; in  main.js or not   It will still work  because of my edit in jquery.terminal.min.js file.

**Comment by sachincool** [comment]
@Logan1x   could you please verify ?  If It's working or not ? 
download my Fork,  And  open Index.html  Locally

**Comment by Logan1x** [comment]
working totally fine for me @sachincool  @sr6033  see
ezgif-4-f7a294ba64

**Comment by sachincool** [comment]
@Logan1x  Thankyou so much, but the problem was   After you execute  "clear" command   and  execute "help" does  it show in the  screen that `clear >  Completed`    like  the echo command in the gif.

**Comment by Logan1x** [comment]
screenshot from 2017-12-29 22-52-23

Yup showing.

**Comment by sr6033** [comment]
Yeah. I am sorry. I was actually looking at my old repo which was not updated. It is working fine.

**Comment by ms10398** [comment]
Checked it its working on my end too
@sr6033 I think you should check again

**Pull request merged**
